additive        ::= multiplicative { ("+" | "-") multiplicative }
multiplicative  ::= power { ("*" | "/") power }
power           ::= unary "**" power | unary
unary           ::= { "-" | "+" } factorial
factorial       ::= parentheses { "!" }
parentheses     ::= "(" additive ")" | integer

integer ::= <digit> { <digit> }
